<?php
//namespace app\commands;
namespace console\controllers;

use common\controllers\Email;
//use app\models\Call;
use \swoole\SwooleServer;
use \yii\console\Controller;

/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 2016/9/12
 * Time: 10:45
 */
class SwooleController extends Controller
{
    public static $redis = null;
    public static $Email = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::setAlias('swoole', dirname(dirname(__DIR__)) . '/swoole');
        if (self::$redis === null) {
            $redis = new \Redis();
            $redis->connect(\Yii::$app->params['redis']['host'], \Yii::$app->params['redis']['port']);
            self::$redis = $redis;
        }
        if (self::$Email === null) {
            self::$Email = new Email();
        }
    }

    public function actionIndex($message = 'start')
    {
        $db        = \Yii::$app->db;
        $config    = \Yii::$app->params['swoole'];
        $masterPid = self::$redis->get('swoolePid');
        switch ($message) {
            case 'start':
                if (empty($masterPid)) {
                    (new SwooleServer(self::$Email, $db, self::$redis, $config))->start();
                } else {
                    print_r('Server is already running. Please stop it first.');
                    return;
                }
            case 'reload':
                if (!empty($masterPid)) {
                    posix_kill($masterPid, SIGUSR1); // 重启所有worker
                    posix_kill($masterPid, SIGUSR2); // 重启所有task
                } else {
                    print_r('master pid is null, maybe you delete the pid file we created. you can manually kill the master process with signal SIGUSR1.');
                }
                break;
            case 'stop':
                if (!empty($masterPid)) {
                    posix_kill($masterPid, SIGTERM);
                } else {
                    print_r('master pid is null, maybe you delete the pid file we created. you can manually kill the master process with signal SIGTERM.');
                }
                break;
            case 'kill':
                self::$redis->del('swoolePid');
                break;
            default:
                print_r("php {$message} start|reload|stop");
                break;
        }
    }

}
